### ISSUE TITLE
Supported KayakFrist devices

### ISSUE THREAD

**Issue by Abasz** [TrackMyIndoorWorkout/TrackMyIndoorWorkout.github.io#34]
We have a rather old KF machine that is orange. I wonder whether that is supported?

Thanks

**Comment by MrCsabaToth** [comment]
Thanks for bringing this up! The support is for the blue devices. I'll have to include that information on the website to avoid confusion, so that will be this ticket's task.

However it'd be great to support the orange ones as well, and I'll follow up about that at https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/issues/492
